

############################################################
# $WORLD_NAME
############################################################
FROM alpine:3.12.1 as $WORLD_NAME

WORKDIR /tmp
COPY .tools/build tools

COPY $WORLD_NAME $WORLD_NAME
RUN tools/buildMap.sh ./$WORLD_NAME

RUN rm -rf /tmp
