############################################################
# FINAL STEP
############################################################

FROM alpine:3.12.1

WORKDIR /tmp
COPY .tools/build tools

RUN mkdir /out
