name: Continuous Integration

on:
  push:
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from GitHub
      uses: actions/checkout@v2
    - name: Generate Dockerfile
      run: .tools/generate-dockerfile/entrypoint.sh
    - name: Print Dockerfile
      run: cat Dockerfile
    - name: Build and publish to registry
      uses: elgohr/Publish-Docker-Github-Action@2.22
      with:
        name: gruppeadler/maps
        tags: "data"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: ${{ github.event_name != 'schedule' }}
        no_push: ${{ github.ref != 'refs/heads/master' }}
